export const WORDS = [
  'code',
  'frontend',
  'process',
  'programming',
  'backend',
  'algorithm',
  'debugging',
  'function',
  'syntax',
  'variable',
  'loop',
  'conditional',
  'database',
  'API',
  'framework',
  'iteration',
  'optimization',
  'bug',
  'class',
  'method',
  'recursion',
  'version control',
  'testing',
  'integration',
  'deployment',
  'responsive design',
  'user interface',
  'responsive web design',
  'DOM manipulation',
  'AJAX',
  'server',
  'client',
  'responsive layout',
  'security',
  'web development',
  'CSS',
  'HTML',
  'JavaScript',
  'React',
  'Vue',
  'Angular',
  'Node.js',
  'PHP',
  'Python',
  'Java',
  'C++',
  'C#',
  'Ruby',
  'Swift',
  'Git',
  'SQL',
  'MongoDB',
  'WordPress',
  'ASP.NET',
  'Django',
  'Flask',
];
export const KEYBOARD_LETTERS = Array.from('ABCDEFGHIJKLMNOPQRSTUVWXYZ');
